name: Push squashed history into public repo

on:
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main

jobs:
  squash:
    name: Do the thing
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Squash history
        run: |
          git config user.email "adps.rpi@gmail.com"
          git config user.name "RPI ADPS"
          git reset $(git commit-tree "HEAD^{tree}" -m "$(date)")
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Push
        run: |
          git remote add public https://github.com/rpiadps/rpiadps.info
          git push public main -f
